services:
  - type: web
    name: landscape-ai-agent
    env: python
    pythonVersion: "3.11"
    buildCommand: "pip install gunicorn && pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker api.index:app"
    envVars:
      - key: WEB_API_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: SPREADSHEET_ID
        sync: false
